// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: processor.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HandlerRegisterResponse_Status int32

const (
	HandlerRegisterResponse_STATUS_UNSET HandlerRegisterResponse_Status = 0
	HandlerRegisterResponse_OK           HandlerRegisterResponse_Status = 1
	HandlerRegisterResponse_ERROR        HandlerRegisterResponse_Status = 2
)

// Enum value maps for HandlerRegisterResponse_Status.
var (
	HandlerRegisterResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "ERROR",
	}
	HandlerRegisterResponse_Status_value = map[string]int32{
		"STATUS_UNSET": 0,
		"OK":           1,
		"ERROR":        2,
	}
)

func (x HandlerRegisterResponse_Status) Enum() *HandlerRegisterResponse_Status {
	p := new(HandlerRegisterResponse_Status)
	*p = x
	return p
}

func (x HandlerRegisterResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandlerRegisterResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_processor_proto_enumTypes[0].Descriptor()
}

func (HandlerRegisterResponse_Status) Type() protoreflect.EnumType {
	return &file_processor_proto_enumTypes[0]
}

func (x HandlerRegisterResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandlerRegisterResponse_Status.Descriptor instead.
func (HandlerRegisterResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{1, 0}
}

// The registration request from the signer processor to the
// signer node
type HandlerRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The cryptographic scheme to be registered
	// For example: tbls256
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
}

func (x *HandlerRegisterRequest) Reset() {
	*x = HandlerRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRegisterRequest) ProtoMessage() {}

func (x *HandlerRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRegisterRequest.ProtoReflect.Descriptor instead.
func (*HandlerRegisterRequest) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerRegisterRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

// A response sent from the signer node to the signer processor
// acknowledging the registration
type HandlerRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status HandlerRegisterResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=HandlerRegisterResponse_Status" json:"status,omitempty"`
}

func (x *HandlerRegisterResponse) Reset() {
	*x = HandlerRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_processor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerRegisterResponse) ProtoMessage() {}

func (x *HandlerRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerRegisterResponse.ProtoReflect.Descriptor instead.
func (*HandlerRegisterResponse) Descriptor() ([]byte, []int) {
	return file_processor_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerRegisterResponse) GetStatus() HandlerRegisterResponse_Status {
	if x != nil {
		return x.Status
	}
	return HandlerRegisterResponse_STATUS_UNSET
}

var File_processor_proto protoreflect.FileDescriptor

var file_processor_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x16, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x17, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53,
	0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x1d, 0x0a, 0x15, 0x73, 0x61, 0x77, 0x74, 0x6f,
	0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x50, 0x01, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_processor_proto_rawDescOnce sync.Once
	file_processor_proto_rawDescData = file_processor_proto_rawDesc
)

func file_processor_proto_rawDescGZIP() []byte {
	file_processor_proto_rawDescOnce.Do(func() {
		file_processor_proto_rawDescData = protoimpl.X.CompressGZIP(file_processor_proto_rawDescData)
	})
	return file_processor_proto_rawDescData
}

var file_processor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_processor_proto_goTypes = []interface{}{
	(HandlerRegisterResponse_Status)(0), // 0: HandlerRegisterResponse.Status
	(*HandlerRegisterRequest)(nil),      // 1: HandlerRegisterRequest
	(*HandlerRegisterResponse)(nil),     // 2: HandlerRegisterResponse
}
var file_processor_proto_depIdxs = []int32{
	0, // 0: HandlerRegisterResponse.status:type_name -> HandlerRegisterResponse.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_processor_proto_init() }
func file_processor_proto_init() {
	if File_processor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_processor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_processor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_processor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_processor_proto_goTypes,
		DependencyIndexes: file_processor_proto_depIdxs,
		EnumInfos:         file_processor_proto_enumTypes,
		MessageInfos:      file_processor_proto_msgTypes,
	}.Build()
	File_processor_proto = out.File
	file_processor_proto_rawDesc = nil
	file_processor_proto_goTypes = nil
	file_processor_proto_depIdxs = nil
}
