name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Update packages
      run: sudo apt-get update
    - name: Install libzmq
      run: sudo apt-get install zeromq

    - name: Test
      run: go test -v ./...
